// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ti4Companion.ApiService.Data;

#nullable disable

namespace Ti4Companion.ApiService.Data.MasterMigrations
{
    [DbContext(typeof(MasterDbContext))]
    [Migration("20260621162415_AddFactionColorsComplexity")]
    partial class AddFactionColorsComplexity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Ti4Companion.ApiService.Data.ActionCard", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Expansion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FlavorText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FlavorTextDe")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NameDe")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TextDe")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Slug", "Version")
                        .IsUnique();

                    b.ToTable("ActionCards");
                });

            modelBuilder.Entity("Ti4Companion.ApiService.Data.AgendaDef", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Elect")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Expansion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NameDe")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("RemovedInPok")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TextDe")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Slug", "Version")
                        .IsUnique();

                    b.ToTable("Agendas");
                });

            modelBuilder.Entity("Ti4Companion.ApiService.Data.Breakthrough", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ConnectedColor1")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ConnectedColor2")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FactionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NameDe")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TextDe")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FactionId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Breakthroughs");
                });

            modelBuilder.Entity("Ti4Companion.ApiService.Data.Exploration", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Deck")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Expansion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NameDe")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TextDe")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Slug", "Version")
                        .IsUnique();

                    b.ToTable("Explorations");
                });

            modelBuilder.Entity("Ti4Companion.ApiService.Data.Faction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Complexity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Expansion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FlavorText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FlavorTextDe")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IconPath")
                        .HasColumnType("TEXT");

                    b.Property<int?>("InitiativeOverride")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NameDe")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("PreferredColors")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("StartingTechnologies")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Slug", "Version")
                        .IsUnique();

                    b.ToTable("Factions");
                });

            modelBuilder.Entity("Ti4Companion.ApiService.Data.FactionAbility", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Expansion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FactionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NameDe")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TextDe")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FactionId");

                    b.HasIndex("Slug", "Version")
                        .IsUnique();

                    b.ToTable("FactionAbilities");
                });

            modelBuilder.Entity("Ti4Companion.ApiService.Data.FactionCard", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Expansion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FactionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NameDe")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TextDe")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FactionId");

                    b.HasIndex("Slug", "Version")
                        .IsUnique();

                    b.ToTable("FactionCards");
                });

            modelBuilder.Entity("Ti4Companion.ApiService.Data.FactionStartingUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FactionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UnitId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FactionId");

                    b.ToTable("FactionStartingUnits");
                });

            modelBuilder.Entity("Ti4Companion.ApiService.Data.GalacticEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Expansion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NameDe")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TextDe")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Slug", "Version")
                        .IsUnique();

                    b.ToTable("GalacticEvents");
                });

            modelBuilder.Entity("Ti4Companion.ApiService.Data.Leader", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Expansion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FactionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FlavorText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FlavorTextDe")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LeaderType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NameDe")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TextDe")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UnlockCondition")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UnlockConditionDe")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FactionId");

                    b.HasIndex("Slug", "Version")
                        .IsUnique();

                    b.ToTable("Leaders");
                });

            modelBuilder.Entity("Ti4Companion.ApiService.Data.ObjectiveDef", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Expansion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NameDe")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Phase")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Points")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Requirement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RequirementDe")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Stage")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Slug", "Version")
                        .IsUnique();

                    b.ToTable("Objectives");
                });

            modelBuilder.Entity("Ti4Companion.ApiService.Data.Planet", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Expansion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FlavorText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FlavorTextDe")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("GrantsRelic")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HomeFactionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Influence")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsStation")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Legendary")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LegendaryEffect")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LegendaryEffectDe")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Resources")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SystemTileId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TechSkip1")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TechSkip2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Trait")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Trait2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Slug", "Version")
                        .IsUnique();

                    b.ToTable("Planets");
                });

            modelBuilder.Entity("Ti4Companion.ApiService.Data.PromissoryNote", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Expansion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FactionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NameDe")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TextDe")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FactionId");

                    b.HasIndex("Slug", "Version")
                        .IsUnique();

                    b.ToTable("PromissoryNotes");
                });

            modelBuilder.Entity("Ti4Companion.ApiService.Data.Relic", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Expansion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FlavorText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FlavorTextDe")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NameDe")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TextDe")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Slug", "Version")
                        .IsUnique();

                    b.ToTable("Relics");
                });

            modelBuilder.Entity("Ti4Companion.ApiService.Data.StrategyCardDef", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Expansion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Initiative")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NameDe")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrimaryText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryTextDe")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RevisionLabel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SecondaryText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SecondaryTextDe")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Number", "Version")
                        .IsUnique();

                    b.ToTable("StrategyCards");
                });

            modelBuilder.Entity("Ti4Companion.ApiService.Data.TechnologyDef", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Color")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Expansion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FactionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NameDe")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prerequisites")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TextDe")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UnitType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Slug", "Version")
                        .IsUnique();

                    b.ToTable("Technologies");
                });

            modelBuilder.Entity("Ti4Companion.ApiService.Data.TypeValue", b =>
                {
                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NameDe")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Type", "Value");

                    b.ToTable("TypeValues");
                });

            modelBuilder.Entity("Ti4Companion.ApiService.Data.UnitDef", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Combat")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CombatDice")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Cost")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Expansion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FactionId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Move")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NameDe")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProducedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TextDe")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UnitAbilities")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UnitType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Slug", "Version")
                        .IsUnique();

                    b.ToTable("Units");
                });
#pragma warning restore 612, 618
        }
    }
}
