// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ti4Companion.ApiService.Data;

#nullable disable

namespace Ti4Companion.ApiService.Data.Migrations
{
    [DbContext(typeof(Ti4DbContext))]
    [Migration("20260621134034_RemoveContentTables")]
    partial class RemoveContentTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Ti4Companion.ApiService.Data.AgendaVote", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Choice")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Locked")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Outcome")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Votes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "PlayerId")
                        .IsUnique();

                    b.ToTable("AgendaVotes");
                });

            modelBuilder.Entity("Ti4Companion.ApiService.Data.GameSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("ActiveExpansions")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ActivePlayerId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ActiveStrategyCardId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AgendaVotesHidden")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowEditAllPlayers")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentAgendaId")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentRound")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefaultLanguage")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DisplayMode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JoinCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastActivityUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Paused")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Phase")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RetentionHours")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowTechOverview")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("SpeakerPlayerId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("VotingStarted")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("JoinCode")
                        .IsUnique();

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("Ti4Companion.ApiService.Data.ObjectiveScore", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ScoredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SessionObjectiveId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SessionObjectiveId");

                    b.ToTable("ObjectiveScores");
                });

            modelBuilder.Entity("Ti4Companion.ApiService.Data.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceToken")
                        .HasColumnType("TEXT");

                    b.Property<string>("FactionId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasPassed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Influence")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHost")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsReady")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SeatOrder")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Ti4Companion.ApiService.Data.PlayerStrategyCard", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsExhausted")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("StrategyCardId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("SessionId", "PlayerId");

                    b.ToTable("PlayerStrategyCards");
                });

            modelBuilder.Entity("Ti4Companion.ApiService.Data.PlayerTechnology", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TechnologyId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("SessionId", "PlayerId");

                    b.ToTable("PlayerTechnologies");
                });

            modelBuilder.Entity("Ti4Companion.ApiService.Data.SessionLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ActorPlayerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Detail")
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Phase")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Round")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TargetPlayerId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "TimestampUtc");

                    b.ToTable("SessionLog");
                });

            modelBuilder.Entity("Ti4Companion.ApiService.Data.SessionObjective", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CustomPoints")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ObjectiveId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("RevealedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("SessionObjectives");
                });

            modelBuilder.Entity("Ti4Companion.ApiService.Data.StrategyCardState", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("StrategyCardId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TradeGoods")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "StrategyCardId")
                        .IsUnique();

                    b.ToTable("StrategyCardStates");
                });

            modelBuilder.Entity("Ti4Companion.ApiService.Data.AgendaVote", b =>
                {
                    b.HasOne("Ti4Companion.ApiService.Data.GameSession", "Session")
                        .WithMany("AgendaVotes")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Ti4Companion.ApiService.Data.ObjectiveScore", b =>
                {
                    b.HasOne("Ti4Companion.ApiService.Data.SessionObjective", "SessionObjective")
                        .WithMany("Scores")
                        .HasForeignKey("SessionObjectiveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SessionObjective");
                });

            modelBuilder.Entity("Ti4Companion.ApiService.Data.Player", b =>
                {
                    b.HasOne("Ti4Companion.ApiService.Data.GameSession", "Session")
                        .WithMany("Players")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Ti4Companion.ApiService.Data.PlayerStrategyCard", b =>
                {
                    b.HasOne("Ti4Companion.ApiService.Data.Player", "Player")
                        .WithMany("StrategyCards")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Ti4Companion.ApiService.Data.PlayerTechnology", b =>
                {
                    b.HasOne("Ti4Companion.ApiService.Data.Player", "Player")
                        .WithMany("Technologies")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Ti4Companion.ApiService.Data.SessionLogEntry", b =>
                {
                    b.HasOne("Ti4Companion.ApiService.Data.GameSession", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ti4Companion.ApiService.Data.SessionObjective", b =>
                {
                    b.HasOne("Ti4Companion.ApiService.Data.GameSession", "Session")
                        .WithMany("Objectives")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Ti4Companion.ApiService.Data.StrategyCardState", b =>
                {
                    b.HasOne("Ti4Companion.ApiService.Data.GameSession", "Session")
                        .WithMany("StrategyCardStates")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Ti4Companion.ApiService.Data.GameSession", b =>
                {
                    b.Navigation("AgendaVotes");

                    b.Navigation("Objectives");

                    b.Navigation("Players");

                    b.Navigation("StrategyCardStates");
                });

            modelBuilder.Entity("Ti4Companion.ApiService.Data.Player", b =>
                {
                    b.Navigation("StrategyCards");

                    b.Navigation("Technologies");
                });

            modelBuilder.Entity("Ti4Companion.ApiService.Data.SessionObjective", b =>
                {
                    b.Navigation("Scores");
                });
#pragma warning restore 612, 618
        }
    }
}
