// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Ti4Companion.ApiService.Data;

#nullable disable

namespace Ti4Companion.ApiService.Data.Migrations
{
    [DbContext(typeof(Ti4DbContext))]
    [Migration("20260616001654_RemoveAgendaInfluence")]
    partial class RemoveAgendaInfluence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ti4Companion.ApiService.Data.AgendaDef", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Elect")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Expansion")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameDe")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("RemovedInPok")
                        .HasColumnType("boolean");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TextDe")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Agendas");
                });

            modelBuilder.Entity("Ti4Companion.ApiService.Data.AgendaVote", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Choice")
                        .HasColumnType("text");

                    b.Property<bool>("Locked")
                        .HasColumnType("boolean");

                    b.Property<int>("Outcome")
                        .HasColumnType("integer");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Votes")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "PlayerId")
                        .IsUnique();

                    b.ToTable("AgendaVotes");
                });

            modelBuilder.Entity("Ti4Companion.ApiService.Data.Faction", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Expansion")
                        .HasColumnType("integer");

                    b.Property<string>("IconPath")
                        .HasColumnType("text");

                    b.Property<int?>("InitiativeOverride")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameDe")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("StartingTechnologies")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.ToTable("Factions");
                });

            modelBuilder.Entity("Ti4Companion.ApiService.Data.GameSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("ActiveExpansions")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ActivePlayerId")
                        .HasColumnType("uuid");

                    b.Property<int?>("ActiveStrategyCardId")
                        .HasColumnType("integer");

                    b.Property<bool>("AgendaVotesHidden")
                        .HasColumnType("boolean");

                    b.Property<bool>("AllowEditAllPlayers")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentAgendaId")
                        .HasColumnType("text");

                    b.Property<int>("CurrentRound")
                        .HasColumnType("integer");

                    b.Property<int>("DefaultLanguage")
                        .HasColumnType("integer");

                    b.Property<int>("DisplayMode")
                        .HasColumnType("integer");

                    b.Property<string>("JoinCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastActivityUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Phase")
                        .HasColumnType("integer");

                    b.Property<int>("RetentionHours")
                        .HasColumnType("integer");

                    b.Property<bool>("ShowTechOverview")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("SpeakerPlayerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("JoinCode")
                        .IsUnique();

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("Ti4Companion.ApiService.Data.ObjectiveDef", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("Expansion")
                        .HasColumnType("integer");

                    b.Property<bool>("IsSecret")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameDe")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<string>("Requirement")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequirementDe")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Stage")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Objectives");
                });

            modelBuilder.Entity("Ti4Companion.ApiService.Data.ObjectiveScore", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ScoredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SessionObjectiveId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SessionObjectiveId");

                    b.ToTable("ObjectiveScores");
                });

            modelBuilder.Entity("Ti4Companion.ApiService.Data.Planet", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("Expansion")
                        .HasColumnType("integer");

                    b.Property<string>("HomeFactionId")
                        .HasColumnType("text");

                    b.Property<int>("Influence")
                        .HasColumnType("integer");

                    b.Property<bool>("Legendary")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameDe")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Resources")
                        .HasColumnType("integer");

                    b.Property<int>("Trait")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Planets");
                });

            modelBuilder.Entity("Ti4Companion.ApiService.Data.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DeviceToken")
                        .HasColumnType("text");

                    b.Property<string>("FactionId")
                        .HasColumnType("text");

                    b.Property<bool>("HasPassed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsHost")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsReady")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SeatOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Ti4Companion.ApiService.Data.PlayerStrategyCard", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsExhausted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("StrategyCardId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("SessionId", "PlayerId");

                    b.ToTable("PlayerStrategyCards");
                });

            modelBuilder.Entity("Ti4Companion.ApiService.Data.PlayerTechnology", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("TechnologyId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("SessionId", "PlayerId");

                    b.ToTable("PlayerTechnologies");
                });

            modelBuilder.Entity("Ti4Companion.ApiService.Data.SessionObjective", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CustomName")
                        .HasColumnType("text");

                    b.Property<int?>("CustomPoints")
                        .HasColumnType("integer");

                    b.Property<string>("ObjectiveId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("RevealedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("SessionObjectives");
                });

            modelBuilder.Entity("Ti4Companion.ApiService.Data.StrategyCardDef", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Initiative")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameDe")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrimaryText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrimaryTextDe")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecondaryText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecondaryTextDe")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("StrategyCards");
                });

            modelBuilder.Entity("Ti4Companion.ApiService.Data.StrategyCardState", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("StrategyCardId")
                        .HasColumnType("integer");

                    b.Property<int>("TradeGoods")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "StrategyCardId")
                        .IsUnique();

                    b.ToTable("StrategyCardStates");
                });

            modelBuilder.Entity("Ti4Companion.ApiService.Data.TechnologyDef", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("Color")
                        .HasColumnType("integer");

                    b.Property<int>("Expansion")
                        .HasColumnType("integer");

                    b.Property<string>("FactionId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameDe")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Prerequisites")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TextDe")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UnitType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Technologies");
                });

            modelBuilder.Entity("Ti4Companion.ApiService.Data.UnitDef", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int?>("Capacity")
                        .HasColumnType("integer");

                    b.Property<int?>("Combat")
                        .HasColumnType("integer");

                    b.Property<int>("CombatDice")
                        .HasColumnType("integer");

                    b.Property<int?>("Cost")
                        .HasColumnType("integer");

                    b.Property<int>("Expansion")
                        .HasColumnType("integer");

                    b.Property<string>("FactionId")
                        .HasColumnType("text");

                    b.Property<int?>("Move")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameDe")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProducedCount")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TextDe")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UnitAbilities")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UnitType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("Ti4Companion.ApiService.Data.AgendaVote", b =>
                {
                    b.HasOne("Ti4Companion.ApiService.Data.GameSession", "Session")
                        .WithMany("AgendaVotes")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Ti4Companion.ApiService.Data.ObjectiveScore", b =>
                {
                    b.HasOne("Ti4Companion.ApiService.Data.SessionObjective", "SessionObjective")
                        .WithMany("Scores")
                        .HasForeignKey("SessionObjectiveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SessionObjective");
                });

            modelBuilder.Entity("Ti4Companion.ApiService.Data.Player", b =>
                {
                    b.HasOne("Ti4Companion.ApiService.Data.GameSession", "Session")
                        .WithMany("Players")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Ti4Companion.ApiService.Data.PlayerStrategyCard", b =>
                {
                    b.HasOne("Ti4Companion.ApiService.Data.Player", "Player")
                        .WithMany("StrategyCards")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Ti4Companion.ApiService.Data.PlayerTechnology", b =>
                {
                    b.HasOne("Ti4Companion.ApiService.Data.Player", "Player")
                        .WithMany("Technologies")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Ti4Companion.ApiService.Data.SessionObjective", b =>
                {
                    b.HasOne("Ti4Companion.ApiService.Data.GameSession", "Session")
                        .WithMany("Objectives")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Ti4Companion.ApiService.Data.StrategyCardState", b =>
                {
                    b.HasOne("Ti4Companion.ApiService.Data.GameSession", "Session")
                        .WithMany("StrategyCardStates")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Ti4Companion.ApiService.Data.GameSession", b =>
                {
                    b.Navigation("AgendaVotes");

                    b.Navigation("Objectives");

                    b.Navigation("Players");

                    b.Navigation("StrategyCardStates");
                });

            modelBuilder.Entity("Ti4Companion.ApiService.Data.Player", b =>
                {
                    b.Navigation("StrategyCards");

                    b.Navigation("Technologies");
                });

            modelBuilder.Entity("Ti4Companion.ApiService.Data.SessionObjective", b =>
                {
                    b.Navigation("Scores");
                });
#pragma warning restore 612, 618
        }
    }
}
